config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

  get '/about',  to: 'pages#about'
  get '/contact',  to: 'pages#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post #asociates comments with post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy#asociate posts with comments

    #makes sure there is at least 5 char in title and content in title and body
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end

    def contact
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #devise settings
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @posts = Post.all.order('created_at DESC') #Get all posts and order them desc by creatin date
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params) #defined below in private

        if
            @post.save          #If the post is saved
            redirect_to @post   #Go to that post
        else
            render 'new'        #otherwise, render the new template again (with content intact)
        end
    end

    def show
        @post = Post.find(params[:id]) #find posts by ID.
    end

    def edit
        @post = Post.find(params[:id]) #find posts to edit by ID
    end

    def update
        @post = Post.find(params[:id])
        if
            @post.update(params[:post].permit(:title, :body))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])  #find item
        @post.destroy                   #destroy it
        redirect_to root_path           #redirect to root
    end

    private
        # strong parameters - what is allowed to be saved. In this case title and body.
        def post_params
            params.require(:post).permit(:title, :body)
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment-content">
        <p class="comment-name"><strong><%= comment.name %></strong></p>
        <p class="comment-body"><%= comment.body %></p>
        <p class="comment-time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>

    <p>
        <% if user_signed_in? %>
            <%= link_to 'Delete Comment', [comment.post, comment], class: 'button', method: :delete,  data: {confirm: 'Are you sure?'} %>
        <% end %>
    </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %><br>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="sidebar">
        <div class="logo">
            <%= link_to root_path do %>
                <%= image_tag "128.jpg" %>
            <% end %>
        </div>

        <ul>
            <li class="category">Website</li>
            <li><%= link_to "Blog", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>

        <ul>
            <li class="category">Social</li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Dribbble</a></li>
            <li><a href="#">Youtube</a></li>
        </ul>

        <% if !user_signed_in? %>
            <p class="sign-in">
                <%= link_to 'Admin Login', new_user_session_path %>
            </p>
        <% end %>

    </div><!-- .sidebar -->

    <div class="main-content">
        <div class="header">

            <% if current_page?(root_path) %>
                <p>All posts</p>
            <% elsif current_page?(about_path) %>
                <p>About</p>
            <% elsif current_page?(contact_path) %>
                <p>Contact</p>
            <% else %>
                <%= link_to "< Back to all posts", root_path  %>
            <% end %>

            <% if user_signed_in? %>
                <div class="buttons">
                    <button class="button"><%= link_to "New Post", new_post_path %></button>
                    <button class="button"><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></button>
                </div>
            <% else %>
                <div class="buttons">
                    <button class="button"><%= link_to 'Log In', new_user_session_path %></button>
                </div>
            <% end %>

        </div>

        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert") %>
        <% end %>

        <%= yield %>

    </div><!-- .main-content -->


</body>
</html>

app/views/pages/about.html.erb
<div class="page-wrapper">

  <div class="profile-image">
    <%= image_tag "http://placehold.it/230x230" %>
  </div>

  <div class="content">
    <h1>Hey, I'm Random Randomsson</h1>
    <p>Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.</p>
    <p>This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.</p>
    <p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter <a href="http://twitter.com/mackenziechild">@MackenzieChild</a> or on the web at <a href="http://mackenziechild.me">mackenziechild.me</a>, and get my posts and exclusive content in your inbox by signing up for my newsletter <a href="http://eepurl.com/02olT">here</a>.</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="page-wrapper">
    <h1>Contact me!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque aperiam porro, odit tenetur repellat ea iusto culpa nulla nobis. Voluptate eos, cum aut corporis sunt, neque nisi! Odio, sit, illum.</p>
</div>

app/views/posts/_form.html.erb
    <%
    #this is a form partial
    # By using @post in form_for - rails is smart enough to know
    # if NEW or EDIT is being used. Sweet.
     %>

    <%= form_for @post do |f| %>

    <!-- error messages -->
    <% if @post.errors.any? %>

        <div class="errors">
            <h2><%= pluralize(@post.errors.count, 'error') %> prevented this post from saving</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>

    <% end %>

    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :body %> <br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>

    <% end %>

app/views/posts/edit.html.erb
<div class="page-wrapper">
    <small><em>This is the "Posts NEW" template</em></small>
    <h2>Edit Post</h2>

    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post-wrapper">
       <h2 class="post-title"><%= link_to post.title, post %></h2>
       <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div class="page-wrapper">
    <small><em>This is the "Posts NEW" template</em></small>

    <%= form_for :post, url: posts_path do |f| %>

    <!-- error messages -->
    <% if @post.errors.any? %>

        <div class="errors">
            <h2><%= pluralize(@post.errors.count, 'error') %> prevented this post from saving</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>

    <% end %>

    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :body %> <br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>

    <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-content">

    <h1 class="title"><%= @post.title %></h1>
    <p class="date">
        submitted: <%= time_ago_in_words(@post.created_at) %> ago.

        <% if user_signed_in? %>
            | <%= link_to 'Edit', edit_post_path(@post), class: "edit-link" %>
            | <%= link_to 'Delete', post_path(@post), class: "delete-link", method: :delete, data: { confirm: 'are you sure you want to delete this post?'} %>
        <% end %>

    </p>
    <p class="body">
        <%= @post.body %>
    </p>

    <div class="comments">
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>

        <h3>Add a comment</h3>
        <%= render "comments/form" %>
    </div>


</div>